name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  e2e_test:
    name: E2E Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ./../../action.yml
        with:
          package-name: dart