name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  e2e_test:
    name: E2E Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: make dummy file for test
        run: |
            echo "dart 2.0.0
            nodejs 14.0.0" >> .tool-versions
      - uses: ./
        id: target
        with:
          package-name: dart
      - name: assert
        run: |
          if [ "2.0.0" != "${{ steps.target.outputs.version }}" ]; then
            exit 1
          fi
  check-dist:
    name: Check dist
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: git status -s
      - run: |
          if [ -n "$( git status -s )" ]; then
            echo "Please commit dist files"
            exit 1
          fi